# ecommerce deployment yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ecomm-deployment
  labels:
    app: ecommerce
spec:
  replicas: 3 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true" # Prometheus annotations to scrape
        prometheus.io/path: "metrics"
      labels:
        app: ecommerce
    spec:
      containers:
      - name: cart #1st container
        image: karthequian/ecomm-cart:latest #Dockerhub image
        ports:
        - containerPort: 8080 #Exposes the port 8080 of the container
        env:
        - name: PORT #Env variable key passed to container that is read by app
          value: "8080" # Value of the env port.
      - name: catalog #2nd container
        image: karthequian/ecomm-catalog:latest
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
      - name: auth #3rd container
        image: karthequian/ecomm-users:latest
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
      - name: jaeger-agent # Required for Jaeger telemetry
        image: jaegertracing/jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        env:
        - name: JAEGER_SERVICE_NAME
          value: cart
        - name: JAEGER_AGENT_HOST
          value: jaeger-all-in-one-agent
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        args: ["--collector.host-port=jaeger-collector.default.svc:14267"]
---
kind: Service
apiVersion: v1
metadata:
  name: ecommerce-service
  labels:
    app: ecommerce-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ecommerce
  ports:
  - name: ecommerce-cart-port
    protocol: TCP
    port: 8080
  - name: ecommerce-users-port
    protocol: TCP
    port: 8082
  - name: ecommerce-catalog-port
    protocol: TCP
    port: 8081
---
